#!/usr/bin/bash

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any command fail
set -o errexit

VERSION="3.21.4+200108"
DESTDIR="/var/www/htdocs/limesurvey"

MUNIN_PLUGINS="
	apache_accesses
	apache_processes
	apache_volume
	httpd_memory
"

echo "* Remove unused httpd config files"
HTTPD_CONF_RM="httpd-autoindex.conf
httpd-dav.conf
httpd-default.conf
httpd-info.conf
httpd-languages.conf
httpd-manual.conf
httpd-mpm.conf
httpd-multilang-errordoc.conf
httpd-ssl.conf
httpd-userdir.conf
httpd-vhosts.conf"

for CONF_RM in ${HTTPD_CONF_RM}; do
  rm -f /opt/local/etc/httpd/${CONF_RM}
done

echo "* Install limesurvey"
mkdir -p "${DESTDIR}/releases"
cd "${DESTDIR}/releases"
curl -s -L -O https://download.qutic.com/src/limesurvey/limesurvey${VERSION}.tar.gz
tar xf limesurvey${VERSION}.tar.gz
rm limesurvey${VERSION}.tar.gz
mv limesurvey limesurvey-${VERSION}

echo "* Setup limesurvey"
cd $DESTDIR
ln -nfs $DESTDIR/releases/limesurvey-${VERSION} current
chown -R www:www "$DESTDIR"

echo "* Change www for cronjobs"
usermod -d "$DESTDIR" -s /usr/bin/bash www

echo "* Activate munin plugins"
/opt/qutic/bin/munin-node-plugins ${MUNIN_PLUGINS}

# Configuring image specific packages
echo "* Configuring image specific packages.";
mkdir -p /var/log/httpd/old
mkdir -p /opt/local/etc/httpd/ssl || true
chmod 0640 /opt/local/etc/httpd/ssl
ln -nfs /opt/local/etc/httpd/ssl /opt/local/etc/httpd/tls

echo "* Setup proxysql";
pkg_add https://download.qutic.com/extras/proxysql-1.4.7.tgz || true
mkdir -p /opt/local/var/proxysql
groupadd -g 130 proxysql
useradd -m -s /usr/bin/false -d /opt/local/var/proxysql -u 130 -g proxysql proxysql
chown proxysql:proxysql /opt/local/var/proxysql/
mv /opt/local/etc/proxysql.cnf /opt/local/etc/proxysql.cnf.bak || true
mv /opt/local/var/tmp/proxysql.cnf /opt/local/etc/proxysql.cnf
chmod 0640 /opt/local/etc/proxysql.cnf
chown root:proxysql /opt/local/etc/proxysql.cnf
mv /opt/local/var/tmp/proxysql.xml /opt/local/lib/svc/manifest/proxysql.xml
svccfg import /opt/local/lib/svc/manifest/proxysql.xml
ln -nfs /var/svc/log/pkgsrc-proxysql:default.log /var/log/proxysql_log

# echo "* Enable ipfilter"
# svcadm enable svc:/network/ipfilter:default

echo "* Enable nullmailer"
svcadm enable svc:/pkgsrc/nullmailer:default || true

# Clean up
echo "* Cleaning up."
rm /root/customize

# Prepare image for provisioning
sm-prepare-image -y
