#!/usr/bin/bash

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any command fail
set -o errexit

# 5.2.3+211122
VERSION="3.27.26+211123"
DESTDIR="/var/www/htdocs/limesurvey"

MUNIN_PLUGINS="
	apache_accesses
	apache_processes
	apache_volume
	httpd_memory
"

echo "* Remove unused httpd config files"
HTTPD_CONF_RM="httpd-autoindex.conf
httpd-dav.conf
httpd-default.conf
httpd-info.conf
httpd-languages.conf
httpd-manual.conf
httpd-mpm.conf
httpd-multilang-errordoc.conf
httpd-ssl.conf
httpd-userdir.conf
httpd-vhosts.conf"

for CONF_RM in ${HTTPD_CONF_RM}; do
  rm -f /opt/local/etc/httpd/${CONF_RM}
done

echo "* Install limesurvey"
mkdir -p "${DESTDIR}/releases"
cd "${DESTDIR}/releases"
curl -s -L -O https://download.qutic.com/src/limesurvey/limesurvey${VERSION}.zip
unzip limesurvey${VERSION}.tar.gz
rm limesurvey${VERSION}.zip
mv limesurvey limesurvey-${VERSION}

echo "* Setup limesurvey"
cd $DESTDIR
ln -nfs $DESTDIR/releases/limesurvey-${VERSION} current

# echo "* Install plugins"
# cd "${DESTDIR}/current/plugins"
# curl -s -L -O https://download.qutic.com/src/limesurvey/rootPageRedirect.zip
# mkdir rootPageRedirect
# unzip -d rootPageRedirect rootPageRedirect.zip || true
# rm -rf rootPageRedirect.zip

echo "* Setup access rights"
chown -R www:www "$DESTDIR"

echo "* Change www for cronjobs"
usermod -d "$DESTDIR" -s /usr/bin/bash www

# Configuring image specific packages
echo "* Configuring image specific packages.";
mkdir -p /var/log/httpd/old
mkdir -p /opt/local/etc/httpd/ssl || true
chmod 0640 /opt/local/etc/httpd/ssl
ln -nfs /opt/local/etc/httpd/ssl /opt/local/etc/httpd/tls

echo "* Enable nullmailer"
svcadm enable svc:/pkgsrc/nullmailer:default || true

# Clean up
echo "* Cleaning up."
rm /root/customize

# Prepare image for provisioning
sm-prepare-image -y
